package com.resharding.db;

import com.resharding.config.MigrationProperties;
import com.resharding.config.SegmentsProperties;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.LinkedHashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Проверяет migration-ledger на настоящем PostgreSQL.
 *
 * <p>Unit mock не доказывает поведение UNIQUE/ON CONFLICT и rollback. Здесь
 * подтверждается ключевой контракт: локальные PK разных source DB могут совпадать,
 * identity задаётся глобальным hash key, а ledger и бизнес INSERT атомарны.
 */
@Testcontainers(disabledWithoutDocker = true)
class TargetRowLedgerIntegrationTest {

    @Container
    static final PostgreSQLContainer<?> POSTGRES =
            new PostgreSQLContainer<>("postgres:16-alpine");

    private DataSourceRegistry registry;
    private TargetRowInserter inserter;

    @BeforeEach
    void setUp() throws Exception {
        SegmentsProperties.DatabaseConnectionProperties db =
                new SegmentsProperties.DatabaseConnectionProperties();
        db.setUrl(POSTGRES.getJdbcUrl());
        db.setUsername(POSTGRES.getUsername());
        db.setPassword(POSTGRES.getPassword());
        SegmentsProperties segments = new SegmentsProperties();
        segments.setDatabase(Map.of("db3", db));

        registry = new DataSourceRegistry(segments);
        registry.activate();
        registry.beginOperation();

        MigrationProperties properties = new MigrationProperties();
        inserter = new TargetRowInserter(registry, properties);

        try (Connection connection = registry.get("db3").getConnection();
             var statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS orders");
            statement.execute("DROP TABLE IF EXISTS reshard_migration_ledger");
            statement.execute("""
                    CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        op_id TEXT NOT NULL,
                        payload TEXT NOT NULL
                    )
                    """);
        }
    }

    @AfterEach
    void tearDown() {
        registry.endOperation();
        registry.deactivate();
    }

    @Test
    void sameLocalPrimaryKeyWithDifferentGlobalHashKeysKeepsBothRows() throws Exception {
        // id=42 существует на двух source DB, но разные глобальные hash key —
        // обе логические строки обязаны сохраниться. Повтор hash-db1 — retry.
        assertThat(insert("hash-db1", 42L, "from-db1")).isTrue();
        assertThat(insert("hash-db2", 42L, "from-db2")).isTrue();
        assertThat(insert("hash-db1", 999L, "retry")).isFalse();

        assertThat(rowCount("orders")).isEqualTo(2);
        assertThat(rowCount("reshard_migration_ledger")).isEqualTo(2);
    }

    @Test
    void failedBusinessInsertRollsBackLedgerAndCanBeRetried() throws Exception {
        // NOT NULL ломает business INSERT. Если ledger не в той же транзакции,
        // retry ошибочно посчитает строку уже перенесённой и данные потеряются.
        assertThatThrownBy(() -> insert("hash-rollback", 1L, null))
                .isInstanceOf(TargetRowInsertException.class);

        assertThat(insert("hash-rollback", 1L, "valid")).isTrue();
        assertThat(rowCount("orders")).isEqualTo(1);
        assertThat(rowCount("reshard_migration_ledger")).isEqualTo(1);
    }

    private boolean insert(String hashKey, long sourceId, String payload) {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("id", sourceId);
        row.put("op_id", hashKey);
        row.put("payload", payload);
        return inserter.insertWithLedger(
                "db3", "mig-it", "orders", "op_id", hashKey, row, "id");
    }

    private long rowCount(String table) throws Exception {
        try (Connection connection = registry.get("db3").getConnection();
             var statement = connection.createStatement();
             ResultSet result = statement.executeQuery("SELECT count(*) FROM " + table)) {
            result.next();
            return result.getLong(1);
        }
    }
}
